### ISSUE TITLE
Introduce the parallel tempering scheme.

### ISSUE THREAD

**Issue by BvB93** [nlesc-nano/auto-FOX#103]
Description
------------
* Investigate the viability of the "parallel tempering" approach in expelling ARMC parameters from local minima.
* See also: https://en.wikipedia.org/wiki/Parallel_tempering.

Implementation
----------------
* The ``ARMC`` step-size would play a role analogous to the temperature here. In other words, "high temperature" does in the context of ``ARMC`` does not refer to the movement across the potential energy surface but, instead, movement through the parameter space.
* The ``ARMC`` equivalent of a temperature is defined by (up to) three parameters:
  * The target acceptance rate.
  * The step-size range.
  * The initial value of phi. Note that actual value of phi, at a given super-iteration, is a function of the target acceptance rate; the initial value will merely affect the convergence speed.
* The single ``PhiUpdater`` will have to be replaced with a collection of ``n`` ``PhiUpdaters``, on the keep track of every single temperature phase (so ``n = 2`` in case of a single low- and high-temperature phase). Alternatively, a new ``PhiUpdater`` or ``PhiUpdaterABC`` subclass can be created.
* The ``ARMC`` class itself will likely need little alteration besides the modification of ``ARMC.do_inner()`` and, to a lesser extend, ``ARMC.__call__()``. These changes will be implemented in the ``ARMCPT`` subclass.
* The multi-job runner of ``PackageManager`` is already well-suited for the purpose of running all ``n``-temperature calculations and is unlikely to require any alterations.
* The ``ParamMapping`` class will need to-be altered in order to store all ``n`` parameter sets. This will likely result in the introduction of either a new ``ParamMapping`` or ``ParamMappingABC`` subclass.

To-do
------
- [x] Implement the main ``ARMCPT`` class.
- [x] Ensure the ``ParamMapping`` (sub-)class is parallel tempering-compatible (https://github.com/nlesc-nano/auto-FOX/commit/a2ec63c5ddb65b12494959ba3a88feea510556d5).
- [x] Ensure the ``PhiUpdater`` (sub-)class is parallel tempering-compatible (https://github.com/nlesc-nano/auto-FOX/commit/a2ec63c5ddb65b12494959ba3a88feea510556d5).

**Comment by BvB93** [comment]
* All ``PhiUpdater`` attributes have been changed from scalars to [``numpy.ndarray``](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html) where applicable.
* All ``ParamMapping["param"]`` and ``ParamMapping["param_old"]`` have been changed from [``pandas.Series``](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) to [``pandas.DataFrame``](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

**Comment by BvB93** [comment]
Open question: What is the best point to perform a parameter shift?
1. Use probabilistic shift akin to normal parallel tempering.
2. Perform a deterministic shift at the end of every ARMC sub-iteration.
3. Something in between?

**Comment by iinfant76** [comment]
Could it be a certain acceptance rate ?

**Comment by BvB93** [comment]
Yeah, that's probably for the best.
It gives you the best of both worlds from 2. and 3.
