### ISSUE TITLE
Implement auto-FOX / CP2K interaction

### ISSUE THREAD

**Issue by BvB93** [nlesc-nano/auto-FOX#16]
Implement a procedure for interacting with CP2K; more specifically running MM-MD jobs with CP2K.

**Comment by felipeZ** [comment]
Use Either **Plams** or **QMFlows**

**Comment by BvB93** [comment]
Current status:
- MM-MD template: ~80% finished
- CP2K interaction: ~70-80% finished
- MM forcfield input: ~50% finished

**Comment by BvB93** [comment]
The Auto-FOX/CP2K interaction is live.
Perhaps add an optional qmflows interface in the future?
