### ISSUE TITLE
PBC and  Angle Distribution Function

### ISSUE THREAD

**Issue by lindasheila** [nlesc-nano/auto-FOX#163]
Dear auto-FOX team,

I am a new user. I would to plot the Adf using the  *.xyz file which contains atomic coordinates.  I am wondering how to take into account the cell parameters to the following piece of code https://auto-fox.readthedocs.io/en/latest/1_rdf.html. Or it is not necessary to evaluate the ADF and the RDF?

Thank you 
Linda

**Comment by BvB93** [comment]
Hi Linda,

With the talking of "cell parameters" I assume that you're dealing with a periodic system?
Unfortunately the support for periodic systems is minimal, mostly due to a lack of user-demand up to this point.
While this might change in the future, it is currently not possible to calculate the RDF/ADF as such. 

Regards, Bas

**Comment by BvB93** [comment]
Hi @lindasheila,

As of https://github.com/nlesc-nano/auto-FOX/pull/225 periodic calculations are now fully supported for both RDF and ADF calculations. If one is interested in performing such calculations then two things have to be done:

* The `MultiMolecule.lattice` property will have to be set. One can provide either a `(3, 3)` matrix or, if the lattice vectors change over the course of the trajectory, a `(n, 3, 3)` array where each frame has its own individual matrix.
* The `periodic` parameter has to be specified in the RDF/ADF constructor, _i.e._ any combination of `x`, `y` and/or `z`.

Examples
----------
``` python
from FOX import MultiMolecule
import numpy as np

mol = MultiMolecule.from_xyz(...)
mol.lattice = np.array(...)  # A `3, 3` or `n, 3, 3` array with lattice vectors

# `xyz` means periodic along both the x, y and z axes
rdf = mol.init_rdf(periodic="xyz")
adf = mol.init_adf(periodic="xyz")
```
