### ISSUE TITLE
XYZ 

### ISSUE THREAD

**Issue by maxsw2** [nlesc-nano/auto-FOX#276]

**Comment by maxsw2** [comment]
Hi, 

I am new to AUTO-FOX, but it seems that I can not transfer the file onto MultiMolecule.

mol = FOX.MultiMolecule.from_xyz("oxygens.xyz")
[oxygens.txt](https://github.com/nlesc-nano/auto-FOX/files/8383471/oxygens.txt)


A non-integer number of molecules was found in 'oxygens.xyz'; mol count: 11.000056414306668

I do not really understand this error because the my xyz is in a correct format. Any help would be appreciated.

**Comment by BvB93** [comment]
Hi @maxsw2,

There are currently two trailing empty lanes at the end of the .xyz file, removing them should resolve the issue.
In the future it might be worthwhile to make the .xyz parser a bit less strict, but for now the fix above should do the trick.
